# action.yml
name: 'Kodi addon submitter action'
description: 'Automatically submits your addon to the official repository when creating a new tag'
inputs:
  kodi-repository:  # Kodi repository project name (repo-scripts for github.com/xbmc/repo-scripts or repo-plugins for github.com/xbmc/repo-plugins)
    description: 'Minimal kodi version where this addon should work (gotham, helix, isengard, jarvis, krypton, leia, matrix)'
    required: true
    default: 'leia'
  kodi-version:  # repo-scripts for github.com/xbmc/repo-scripts or repo-plugins for github.com/xbmc/repo-plugins
    description: 'Repository name (repo-scripts for github.com/xbmc/repo-scripts or repo-plugins for github.com/xbmc/repo-plugins)'
    required: true
    default: 'repo-plugins'
  addon-id:
    description: 'Your addon id'
    required: true
    default: ''
  kodi-matrix:
    description: 'Submit a Python 2/3 compatible addon to matrix branch in addition to the target branch'
    required: false
    default: false
  sub-directory:
    description: 'Addon is stored in its own directory within the git repo'
    required: false
    default: false
  push-only:
    description: 'Only push to your repo fork and not create a pull request'
    required: false
    default: false
outputs:
    addon-zip:
        description: 'The path to the zip file of the addon'
    addon-zip-matrix:
        description: 'The path to the zip file of the addon release for matrix (PEP440 local version identifier) if kodi-matrix input is true.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.kodi-repository }}
    - ${{ inputs.kodi-version }}
    - ${{ inputs.addon-id }}
    - ${{ inputs.kodi-matrix }}
    - ${{ inputs.sub-directory }}
    - ${{ inputs.push-only }}
